[env:esp32-h2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-h2-devkitm-1
framework = arduino

monitor_speed = 115200

; Раздел флеша с местом под хранилище Zigbee — тот же файл, что и в магнитоле
board_build.partitions = zigbee.csv

build_flags =
    ; USB CDC — чтобы Serial работал через встроенный USB
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    ; ZCZR = Coordinator/Router. Без этого флага Zigbee не соберётся
    -DZIGBEE_MODE_ZCZR
    ; Уровень логов ядра: 3 = ошибки и предупреждения
    -DCORE_DEBUG_LEVEL=3

; Библиотека для вывода на адресную ленту (WS2811/SK6812-подобные) через RMT
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3
